name: Deploy Saleor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Download Docker & Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker.io docker-compose -y
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build and test containers
        run: |
          docker compose up -d --build

      - name: wait 20 seconds
        run: sleep 20

      - name: Test GraphQL API
        run: |
          curl -X POST http://localhost:8000/graphql/ \
            -H "Content-Type: application/json" \
            -d '{"query": "{ __typename }"}'
