name: CI/CD Saleor

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: dwnl Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Collect and up services
        run: docker compose up -d db redis jaeger mailpit

      - name: Entry tests in saleor api
        run: docker compose run --rm api python manage.py test

      - name: start all services
        run: docker compose up -d
