name: Deploy Saleor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Настроить Docker
        uses: docker/setup-buildx-action@v3

      - name: Авторизация в Docker (необязательно, если не пушишь в DockerHub)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Запустить контейнеры через Docker Compose
        run: |
          docker compose up -d --build

      - name: Подождать 20 секунд (для запуска контейнеров)
        run: sleep 20

      - name: Протестировать GraphQL API
        run: |
          curl -X POST http://localhost:8000/graphql/ \
            -H "Content-Type: application/json" \
            -d '{"query": "{ __typename }"}'
